### ISSUE TITLE
Conflict new flutter version [2.5.0]

### ISSUE THREAD

**Issue by lqmminh** [Idean/Flutter-Neumorphic#238] opened 2021-09-10 12:00 UTC
Conflict new flutter version [2.5.0]

**Comment by ndahlquist** [comment] 2021-09-10 21:05
Note: this issue is a duplicate of #227. There is a workaround there, and a PR open here to fix the issue: https://github.com/Idean/Flutter-Neumorphic/pull/228.

**Comment by lqmminh** [comment] 2021-09-11 11:01
okay

**Closed** 2021-09-11 11:01 UTC
